version: '3.7'
services:

  # The core platform, mounts docker control socket and route definition into the image
  csp-mno-3:
    image: ashokkumarta/ids-trusted-connector
    pull_policy: always
    tty: true
    stdin_open: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../deploy/allow-all-flows.pl:/root/deploy/allow-all-flows.pl
      - ../etc/settings3.mapdb:/root/etc/settings.mapdb
      - ../etc/csp-mno-3.p12:/root/etc/csp-mno-3.p12
      - ../etc/truststore.p12:/root/etc/truststore.p12
      - ./csp-mno-3.xml:/root/deploy/csp-mno-3.xml
    # Enable this port mappings for debugging or UI access from localhost
    ports:
      - "8083:8080"
    networks:
      - ids-local

  mno3-performance:
    image: ashokkumarta/mno3-sharing-agent-app
    pull_policy: always
    networks:
      - ids-local

networks:
  ids-local:
    driver: bridge
    